uploads = []
generated = []

[[outputs]]
id = "VOn4Hozv6TbjdFo3t35Ug"
uri = "file://masterbo.zip"
type = "unspecified"
title = "masterbo.zip"
description = "Архив исходников проекта Masterbo без временных зависимостей и базы данных."
logical_id = "ea77738b-bdb7-444e-a033-10d65ac67e0f"
content_hash = "sha256:737dd7274e5501a631a0d8570abbb95d9b03a16b69545ceea5aaa87b618bbb5d"
size = 27599
mtime_ms = 1789683201254
storage_uri = "gcs://replit-rams-assets-pike/rams/assets/repl:9b7b76e6-2a55-4066-aec3-8b9aabd72cfa/ea77738b-bdb7-444e-a033-10d65ac67e0f/bf29c326-4a75-4adf-b4ec-42dc47fbeac5"
storage_version_token = "1789683206990420"
content_type = "application/octet-stream"
